[package]
name = "gitui"
version = "0.20.1"
authors = ["extrawurst <mail@rusticorn.com>"]
description = "blazing fast terminal-ui for git"
edition = "2018"
rust-version = "1.50"
exclude = [".github/*", ".vscode/*", "assets/*"]
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = [
    "git",
    "gui",
    "cli",
    "terminal",
    "ui",
]

[dependencies]
anyhow = "1.0"
asyncgit = { path = "./asyncgit", version = "0.21", default-features = false }
backtrace = "0.3"
bitflags = "1.3"
bugreport = "0.5"
bytesize = { version = "1.1", default-features = false }
chrono = "0.4"
clap = { version = "2.33", default-features = false }
crossbeam-channel = "0.5"
crossterm = { version = "0.20", features = [ "serde" ] }
dirs-next = "2.0"
easy-cast = "0.4"
filetreelist = { path = "./filetreelist", version = "0.5" }
fuzzy-matcher = "0.3"
gh-emoji = { version = "1.0", optional = true }
itertools = "0.10"
lazy_static = "1.4"
log = "0.4"
rayon-core = "1.9"
ron = "0.7"
scopeguard = "1.1"
scopetime = { path = "./scopetime", version = "0.1" }
serde = "1.0"
simplelog = { version = "0.11", default-features = false }
syntect = { version = "4.6", default-features = false, features = ["metadata", "default-fancy"] }
textwrap = "0.14"
tui = { version = "0.16", default-features = false, features = ['crossterm', 'serde'] }
unicode-segmentation = "1.9"
unicode-truncate = "0.2"
unicode-width = "0.1"

[target.'cfg(all(target_family="unix",not(target_os="macos")))'.dependencies]
which = "4.2"

# pprof is not available on windows
[target.'cfg(not(windows))'.dependencies]
pprof = { version = "=0.6.1", features = ["flamegraph"], optional = true }

[dev-dependencies]
pretty_assertions = "1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
default =["ghemoji", "trace-libgit"]
ghemoji =["gh-emoji"]
timing =["scopetime/enabled"]
trace-libgit =["asyncgit/trace-libgit"]

[workspace]
members =[
    "asyncgit",
    "filetreelist",
    "scopetime",
]

[profile.release]
lto = true
opt-level = 'z'  # Optimize for size.
codegen-units = 1

# make debug build as fast as release 
# usage of utf8 encoding inside tui 
# makes their debug profile slow
[profile.dev.package."tui"]
opt-level = 3

[profile.dev]
split-debuginfo = "unpacked"
